image: node:10.15.3-jessie

stages:
  - packages
  - lint
  - test
  - build
  - deploy

before_script:
  - ln -s /node_modules node_modules

packages:
  stage: packages
  script: "yarn install && npm rebuild node-sass"

lint:
  stage: lint
  script: "yarn run lint"

test:
  stage: test
#  script: "yarn run test.prod --watch-false"
  script:
    # Installs Chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install google-chrome-stable -y
    # Runs the tests.
    - yarn run test.prod --watch=false
  coverage: '/Statements\s*:\s*([^%]+)/'

build:
  only:
    - develop
  stage: build
  tags: 
    - open360-shell
  before_script:
    - ln -s /home/ci-user/frontend/node_modules node_modules # a bit hacky, rewrite later
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.bw-sw.com:5000
  script: 
    - yarn install --ignore-engines
    - yarn build
    - docker build --tag=git.bw-sw.com:5000/open360/frontend:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID} --file=".docker/bw-assessment-ui.prod.dockerfile" .
    - docker push git.bw-sw.com:5000/open360/frontend:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}


deploy:
  only:
    - develop
  stage: deploy
  tags: 
    - open360-shell
  environment:
    name: Development
    url: http://vm-a834f9ac-1c23-40f2-9461-618361703efd.premium.cs2.netpoint-dc.com
  before_script: 
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.bw-sw.com:5000
  script: 
    - docker rm -f public-bw-assessment-ui || true
    - docker run  -d --restart=always -p  80:80 --name public-bw-assessment-ui git.bw-sw.com:5000/open360/frontend:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}
